feature/ELEC-487 - GET single course API by courseCode
csesoc/cselectives-v2 pull request #189
Opened 2023-05-26 08:33 UTC by vinsentcs

2023-05-26 10:53 UTC, joanna209 requested changes
lgtm so far, just some minor changes 😎

2023-05-26 10:53 UTC, joanna209 commented on backend/src/controllers/course.controller.ts
> +        "/course/page/:courseCode",
nit: could you make this endpoint be `/course/:courseCode` instead of `/course/page/:courseCode`

2023-05-26 10:53 UTC, joanna209 commented on backend/src/controllers/course.controller.ts
> +          this.logger.debug(`Received request in GET /course/page/:courseCode`);
might be good to add tests in course repo

2023-06-03 13:10 UTC, aimenhamed approved these changes

2023-06-03 13:10 UTC, merged